stages:
  - test
  - build

.phpunit-template: &phpunit-template
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  artifacts:
    when: always
    paths:
      - report.xml
      - coverage.xml
    reports:
      junit: report.xml
      cobertura: coverage.xml
    expire_in: 1 week
  script:
    - sed -i 's#../../threema/#vendor/threema/#g' composer.json
    - composer install
    - ./vendor/phpunit/phpunit/phpunit --configuration phpunit.xml --coverage-text --colors=never --log-junit report.xml --coverage-cobertura coverage.xml

phpunit:8.0:
  image: laravelsail/php80-composer:latest
  <<: *phpunit-template

phpunit:8.1:
  image: laravelsail/php81-composer:latest
  <<: *phpunit-template

publish:
  image: curlimages/curl:latest
  stage: build
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    - if [ $code -eq 201 ]; then
        echo "Package created - Code $code - $body";
      else
        echo "Could not create package - Code $code - $body";
        exit 1;
      fi
